Repository hassio-addons/addon-sqlite-web, pull requests merged in 2022-05, with the labels that each got.

#205 ⬆️ Upgrades nginx to 1.20.2-r1
  sqlite-web/Dockerfile
Labels: dependencies

#206 ⬆️ Upgrades add-on base image to 11.1.2
  sqlite-web/Dockerfile
  sqlite-web/build.yaml
Labels: dependencies

#207 Add optional configuration for database location
  sqlite-web/DOCS.md
  sqlite-web/config.yaml
  sqlite-web/rootfs/etc/cont-init.d/sqlite-web.sh
  sqlite-web/rootfs/etc/services.d/sqlite-web/run
  sqlite-web/translations/en.yaml
Labels: new-feature

#208 Replace and/or remove refrences to ludeeus
  README.md
  sqlite-web/.README.j2
  sqlite-web/DOCS.md
  sqlite-web/Dockerfile
  sqlite-web/rootfs/etc/cont-init.d/sqlite-web.sh
  sqlite-web/rootfs/patches/buymeacoffee
Labels: maintenance
